// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// propagateLS__
List propagateLS__(List cqpotList_, List rip);
RcppExport SEXP gRain_propagateLS__(SEXP cqpotList_SEXP, SEXP ripSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type cqpotList_(cqpotList_SEXP);
    Rcpp::traits::input_parameter< List >::type rip(ripSEXP);
    __result = Rcpp::wrap(propagateLS__(cqpotList_, rip));
    return __result;
END_RCPP
}
// sparse_setXtf1
SEXP sparse_setXtf1(SEXP XX_, SEXP TF_);
RcppExport SEXP gRain_sparse_setXtf1(SEXP XX_SEXP, SEXP TF_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type XX_(XX_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type TF_(TF_SEXP);
    __result = Rcpp::wrap(sparse_setXtf1(XX_, TF_));
    return __result;
END_RCPP
}
