# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check__ <- function(cqpotList_) {
    .Call('_gRain_check__', PACKAGE = 'gRain', cqpotList_)
}

propagateLS__ <- function(cqpotList_, rip) {
    .Call('_gRain_propagateLS__', PACKAGE = 'gRain', cqpotList_, rip)
}

.sparse_setXtf1 <- function(XX_, TF_) {
    .Call('_gRain_sparse_setXtf1', PACKAGE = 'gRain', XX_, TF_)
}

